# Generated by Django 5.2.17 on 2026-09-30 19:39

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('nb_facades', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='nombre de façades')),
                ('adresse', models.CharField(blank=True, max_length=200)),
                ('date_entree', models.DateField(blank=True, null=True, verbose_name='occupée depuis')),
                ('date_sortie', models.DateField(blank=True, null=True, verbose_name="occupée jusqu'au")),
                ('surface_m2', models.PositiveIntegerField(blank=True, null=True, verbose_name='surface chauffée (m²)')),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'maison',
                'verbose_name_plural': 'maisons',
                'ordering': ['-date_entree'],
            },
        ),
        migrations.CreateModel(
            name='StationMeteo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('latitude', models.DecimalField(decimal_places=5, max_digits=8)),
                ('longitude', models.DecimalField(decimal_places=5, max_digits=8)),
                ('base_dj', models.DecimalField(decimal_places=1, default=Decimal('16.5'), help_text='16.5 = convention belge (DJ 16.5/16.5).', max_digits=4, verbose_name='base des degrés-jours (°C)')),
            ],
            options={
                'verbose_name': 'station météo',
                'verbose_name_plural': 'stations météo',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('energie', models.CharField(blank=True, choices=[('EAU', 'Eau'), ('GAZ', 'Gaz'), ('ELEC', 'Électricité')], help_text="Laisser vide si l'événement concerne toutes les énergies.", max_length=5)),
                ('date', models.DateField()),
                ('libelle', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('maison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evenements', to='suivi.maison')),
            ],
            options={
                'verbose_name': 'événement',
                'verbose_name_plural': 'événements',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Compteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('energie', models.CharField(choices=[('EAU', 'Eau'), ('GAZ', 'Gaz'), ('ELEC', 'Électricité')], max_length=5)),
                ('plage', models.CharField(choices=[('UNIQUE', 'Mono-horaire'), ('HAUT', 'Heures pleines'), ('BAS', 'Heures creuses')], default='UNIQUE', max_length=6)),
                ('libelle', models.CharField(blank=True, max_length=100)),
                ('numero', models.CharField(blank=True, max_length=50, verbose_name='numéro de compteur')),
                ('unite', models.CharField(default='m³', max_length=10)),
                ('coef_kwh', models.DecimalField(decimal_places=3, default=Decimal('1'), help_text="11 pour un compteur gaz en m³, 1 pour l'électricité.", max_digits=6, verbose_name='coefficient de conversion en kWh')),
                ('date_pose', models.DateField(blank=True, null=True)),
                ('date_depose', models.DateField(blank=True, null=True)),
                ('remplace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remplace_par', to='suivi.compteur', verbose_name='remplace le compteur')),
                ('maison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compteurs', to='suivi.maison')),
            ],
            options={
                'verbose_name': 'compteur',
                'verbose_name_plural': 'compteurs',
                'ordering': ['maison', 'energie', 'plage', 'date_pose'],
            },
        ),
        migrations.AddField(
            model_name='maison',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='maisons', to='suivi.stationmeteo'),
        ),
        migrations.CreateModel(
            name='Tarif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('energie', models.CharField(choices=[('EAU', 'Eau'), ('GAZ', 'Gaz'), ('ELEC', 'Électricité')], max_length=5)),
                ('fournisseur', models.CharField(blank=True, max_length=100)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('prix_unitaire', models.DecimalField(decimal_places=5, default=Decimal('0'), help_text="Par unité du compteur : €/m³ pour l'eau et le gaz, €/kWh pour l'électricité.", max_digits=8, verbose_name='prix unitaire (€)')),
                ('abonnement_mensuel', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8, verbose_name='abonnement (€/mois)')),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('maison', models.ForeignKey(blank=True, help_text='Laisser vide pour un tarif applicable à toutes les maisons.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tarifs', to='suivi.maison')),
            ],
            options={
                'verbose_name': 'tarif',
                'verbose_name_plural': 'tarifs',
                'ordering': ['energie', 'date_debut'],
            },
        ),
        migrations.CreateModel(
            name='Releve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('index', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('source', models.CharField(choices=[('MANUEL', 'Relevé manuel'), ('FOURNISSEUR', 'Index fournisseur'), ('ESTIME', 'Estimation'), ('IMPORT', 'Import Excel')], default='MANUEL', max_length=12)),
                ('commentaire', models.CharField(blank=True, max_length=200)),
                ('compteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releves', to='suivi.compteur')),
            ],
            options={
                'verbose_name': 'relevé',
                'verbose_name_plural': 'relevés',
                'ordering': ['compteur', 'date'],
                'indexes': [models.Index(fields=['compteur', 'date'], name='suivi_relev_compteu_05beb3_idx')],
                'constraints': [models.UniqueConstraint(fields=('compteur', 'date'), name='releve_unique_par_compteur_et_date')],
            },
        ),
        migrations.CreateModel(
            name='DegreJour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('temperature_moyenne', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('dj', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='degrés-jours')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='degres_jours', to='suivi.stationmeteo')),
            ],
            options={
                'verbose_name': 'degré-jour',
                'verbose_name_plural': 'degrés-jours',
                'ordering': ['station', 'date'],
                'indexes': [models.Index(fields=['station', 'date'], name='suivi_degre_station_ee19a9_idx')],
                'constraints': [models.UniqueConstraint(fields=('station', 'date'), name='dj_unique_par_station_et_date')],
            },
        ),
    ]
