# Generated by Django 5.2.17 on 2026-10-01 05:47

import suivi.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suivi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='releve',
            name='index_lu_automatiquement',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Valeur reconnue sur la photo avant correction éventuelle. Conservée pour mesurer la fiabilité de la lecture automatique.', max_digits=12, null=True, verbose_name="index proposé par l'OCR"),
        ),
        migrations.AddField(
            model_name='releve',
            name='photo',
            field=models.ImageField(blank=True, help_text="Preuve de l'index, utile en cas de contestation.", null=True, upload_to=suivi.models.chemin_photo, verbose_name='photo du compteur'),
        ),
    ]
