# Generated by Django 5.2.17 on 2026-10-01 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suivi', '0002_releve_index_lu_automatiquement_releve_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='releve',
            name='annuel',
            field=models.BooleanField(default=False, help_text="À cocher pour le relevé qui clôt l'année. Les prévisions et les comparaisons d'une année sur l'autre partent alors de cette date plutôt que du 1er janvier.", verbose_name='relevé annuel'),
        ),
    ]
