# Generated by Django 5.2.17 on 2026-10-03 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suivi', '0003_releve_annuel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compteur',
            name='energie',
            field=models.CharField(choices=[('EAU', 'Eau'), ('GAZ', 'Gaz'), ('ELEC', 'Électricité'), ('MAZ', 'Mazout')], max_length=5),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='energie',
            field=models.CharField(blank=True, choices=[('EAU', 'Eau'), ('GAZ', 'Gaz'), ('ELEC', 'Électricité'), ('MAZ', 'Mazout')], help_text="Laisser vide si l'événement concerne toutes les énergies.", max_length=5),
        ),
        migrations.AlterField(
            model_name='tarif',
            name='energie',
            field=models.CharField(choices=[('EAU', 'Eau'), ('GAZ', 'Gaz'), ('ELEC', 'Électricité'), ('MAZ', 'Mazout')], max_length=5),
        ),
    ]
